### PR TITLE
Nbt rewrite

### LINKED ISSUE #24: Implement SNBT Parsing
Feature Request: Allow for editing nbt data through the SNBT view.

### LINKED ISSUE #36: NBT Data Type Hotkey Additions
You can add a new tag via a button (blue arrow in image). When you do so, it creates the tag below (red arrow in image). Now, currently, before you type anything, you can pre-select the data type by hot keys. For example, push `i` and it swaps to `int`, or push `l` and it swaps to `long`. Then you can immediately start typing without having to click on the text box.

There are a couple data types that don't have this capability - mainly `list` and `string`, probably because `l` and `s` already map to `long` and `short`, respectively. My suggestion: add some hotkeys for those data types. I use those two a lot, and just the added convenience is helpful. Maybe `g` for `string`, and `t` for `list`.

No idea if there are others missing. Thanks!

image

### PR DESCRIPTION
**Pull request by misode**
Depends on https://github.com/misode/deepslate/pull/16

## New features
- Closes #24
- Closes #36

### CODE REVIEW

**Comment by misode** [comment]
This PR has a new beta version. If there are no further issues this will be the version merged to master and published as `0.8.0`.
[vscode-nbt-0.8.0-beta.2.zip](https://github.com/misode/vscode-nbt/files/10356311/vscode-nbt-0.8.0-beta.2.zip) (extract this file and then install the vsix)

**Comment by RatDonkeyGoat** [comment]
https://github.com/misode/vscode-nbt/issues/41#issue-1561220118

**Comment by misode** [comment]
This PR can be tested using this install:
[vscode-nbt-0.8.0-beta.3_UNZIP_ME.zip](https://github.com/misode/vscode-nbt/files/10531555/vscode-nbt-0.8.0-beta.3_UNZIP_ME.zip)

**Comment by RatDonkeyGoat** [comment]
same issue using the beta 3 version 

i am using snbt to edit the files that probably is why you didnt have the same issue

https://github.com/misode/vscode-nbt/issues/42#issue-1561947494

**Comment by misode** [comment]
The issue mentioned above is now fixed in this beta release:
[vscode-nbt-0.8.0-beta.4_UNZIP_ME.zip](https://github.com/misode/vscode-nbt/files/10537763/vscode-nbt-0.8.0-beta.4_UNZIP_ME.zip)

**Comment by RatDonkeyGoat** [comment]
amazing thank you so much! your extension is so helpful <3

**Pull request merged**
